// <auto-generated />
namespace Search_n_View.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addedpolicyyearindocument : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedpolicyyearindocument));
        
        string IMigrationMetadata.Id
        {
            get { return "202112230713117_added policy, year in document"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
